-- Crear tabla app_control
CREATE TABLE public.app_control (
    id_control integer NOT NULL,
    semestre character varying(50),
    anio character varying(4),
    nombre character varying(255),
    compania character varying(255),
    codigo character varying(255),
    tipologia character varying(255),
    frecuencia character varying(255),
    clasificacion character varying(255),
    descripcion_riesgo text,
    naturaleza character varying(255),
    objetivo text,
    conclusion_diseno text,
    ciclo character varying(255),
    descripcion_control text,
    supervisor character varying(255),
    fecha_elaboracion date,
    horas_invertidas integer,
    recursos_consultados text,
    id_subproceso_id integer,
    id_estado_id character varying(10),
    id_usuario_id character varying(255)
);

-- Secuencia para id_control
ALTER TABLE public.app_control ALTER COLUMN id_control ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_control_id_control_seq
    START WITH 1
    INCREMENT BY 1
);

-- Crear tabla app_estado
CREATE TABLE public.app_estado (
    id_estado character varying(10) NOT NULL,
    estado character varying(255) NOT NULL
);

-- Crear tabla app_pregunta
CREATE TABLE public.app_pregunta (
    id_pregunta character varying(255) NOT NULL,
    texto text NOT NULL
);

-- Crear tabla app_prueba
CREATE TABLE public.app_prueba (
    id_prueba integer NOT NULL,
    fecha_ejecucion date NOT NULL,
    ejecutante text NOT NULL,
    comentario_recorrido text NOT NULL,
    id_control_id integer NOT NULL
);

-- Secuencia para id_prueba
ALTER TABLE public.app_prueba ALTER COLUMN id_prueba ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_prueba_id_prueba_seq
    START WITH 1
    INCREMENT BY 1
);

-- Crear tabla app_respuesta
CREATE TABLE public.app_respuesta (
    id_respuesta integer NOT NULL,
    respuesta character varying(255),
    explicacion text,
    id_control_id integer NOT NULL,
    id_pregunta_id character varying(255) NOT NULL
);

-- Secuencia para id_respuesta
ALTER TABLE public.app_respuesta ALTER COLUMN id_respuesta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_respuesta_id_respuesta_seq
    START WITH 1
    INCREMENT BY 1
);

-- Crear tabla app_rol
CREATE TABLE public.app_rol (
    id_rol character varying(10) NOT NULL,
    rol character varying(255) NOT NULL
);

-- Crear tabla app_usuario
CREATE TABLE public.app_usuario (
    id_usuario character varying(255) NOT NULL,
    nombre character varying(255) NOT NULL,
    contrasena character varying(255) NOT NULL,
    rol_id character varying(10) NOT NULL
);

-- Insertar datos
INSERT INTO public.app_control VALUES (22293, '1', '2024', 'Evaluación del modelo', 'Banitsmo', 'BNSTM', 'Verificación', 'Mensual', 'Automático', 'Posibilidad de inconsistencias', 'Detectivo', 'Garantizar la integridad y la exactitud', 'No evaluado', 'IFRS', 'Mensualmente, el analista o científico de datos, realiza la ejecución', 'Supervisor', '2024-11-26', 23, 'Wikipedia', NULL, '2', '123');
INSERT INTO public.app_estado VALUES ('1', 'Sin iniciar');
INSERT INTO public.app_estado VALUES ('2', 'En proceso');
INSERT INTO public.app_estado VALUES ('3', 'Terminado');
INSERT INTO public.app_estado VALUES ('4', 'No evaluado');
INSERT INTO public.app_pregunta VALUES ('2', '¿El control cumple con su objetivo y/o mitiga el riesgo asociado?');
INSERT INTO public.app_pregunta VALUES ('1', '¿El control se ejecuta tal como está descrito?');
INSERT INTO public.app_pregunta VALUES ('3', '¿Las Aseveraciones relacionadas en el control son las que debidamente aplican a este?');
INSERT INTO public.app_pregunta VALUES ('4', '¿El control es preciso que brinda suficiente confianza sobre su efectividad?');
INSERT INTO public.app_prueba VALUES (1, '2024-11-21', 'Bancolombia', 'Excelente', 22293);
INSERT INTO public.app_respuesta VALUES (1, 'si', 'a', 22293, '1');
INSERT INTO public.app_respuesta VALUES (2, 'si', 'b', 22293, '2');
INSERT INTO public.app_respuesta VALUES (3, 'si', 'c', 22293, '3');
INSERT INTO public.app_respuesta VALUES (4, 'si', 'd', 22293, '4');
INSERT INTO public.app_rol VALUES ('1', 'Auditor');
INSERT INTO public.app_usuario VALUES ('123', 'chena', '111', '1');

-- Ajustes de secuencias
SELECT pg_catalog.setval('public.app_control_id_control_seq', 1, false);
SELECT pg_catalog.setval('public.app_prueba_id_prueba_seq', 1, true);
SELECT pg_catalog.setval('public.app_respuesta_id_respuesta_seq', 1, false);

-- Crear claves primarias
ALTER TABLE ONLY public.app_control ADD CONSTRAINT app_control_pkey PRIMARY KEY (id_control);
ALTER TABLE ONLY public.app_estado ADD CONSTRAINT app_estado_pkey PRIMARY KEY (id_estado);
ALTER TABLE ONLY public.app_pregunta ADD CONSTRAINT app_pregunta_pkey PRIMARY KEY (id_pregunta);
ALTER TABLE ONLY public.app_prueba ADD CONSTRAINT app_prueba_pkey PRIMARY KEY (id_prueba);
ALTER TABLE ONLY public.app_respuesta ADD CONSTRAINT app_respuesta_pkey PRIMARY KEY (id_respuesta);
ALTER TABLE ONLY public.app_rol ADD CONSTRAINT app_rol_pkey PRIMARY KEY (id_rol);
ALTER TABLE ONLY public.app_usuario ADD CONSTRAINT app_usuario_pkey PRIMARY KEY (id_usuario);

-- Crear índices
CREATE INDEX app_control_id_estado_id_1bf67ee8 ON public.app_control USING btree (id_estado_id);
CREATE INDEX app_control_id_subproceso_id_98832b66 ON public.app_control USING btree (id_subproceso_id);
CREATE INDEX app_control_id_usuario_id_602765c6 ON public.app_control USING btree (id_usuario_id);
CREATE INDEX app_estado_id_estado_d4a9d4e4_like ON public.app_estado USING btree (id_estado varchar_pattern_ops);
CREATE INDEX app_pregunta_id_pregunta_8416b33a_like ON public.app_pregunta USING btree (id_pregunta varchar_pattern_ops);
CREATE INDEX app_prueba_id_control_id_db7f6157 ON public.app_prueba USING btree (id_control_id);
CREATE INDEX app_respuesta_id_control_id_c5cad6e6 ON public.app_respuesta USING btree (id_control_id);
CREATE INDEX app_respuesta_id_pregunta_id_7a17243d ON public.app_respuesta USING btree (id_pregunta_id);
CREATE INDEX app_rol_id_rol_14b1ceac_like ON public.app_rol USING btree (id_rol varchar_pattern_ops);
CREATE INDEX app_usuario_id_usuario_9002a0f7_like ON public.app_usuario USING btree (id_usuario varchar_pattern_ops);
CREATE INDEX app_usuario_rol_id_4d394560 ON public.app_usuario USING btree (rol_id);

