# Generated by Django 5.1.3 on 2024-11-25 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id_control', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.CharField(max_length=50)),
                ('anio', models.CharField(max_length=4)),
                ('nombre', models.CharField(max_length=255)),
                ('compania', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=255)),
                ('tipologia', models.CharField(max_length=255)),
                ('frecuencia', models.CharField(max_length=255)),
                ('clasificacion', models.CharField(max_length=255)),
                ('descripcion_riesgo', models.TextField()),
                ('naturaleza', models.CharField(max_length=255)),
                ('objetivo', models.TextField()),
                ('conclusion_diseno', models.TextField()),
                ('ciclo', models.CharField(max_length=255)),
                ('descripcion_control', models.TextField()),
                ('supervisor', models.CharField(max_length=255)),
                ('fecha_elaboracion', models.DateField()),
                ('horas_invertidas', models.IntegerField()),
                ('recursos_consultados', models.TextField()),
                ('id_subproceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.control')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id_prueba', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ejecucion', models.DateField()),
                ('ejecutante', models.TextField()),
                ('comentario_recorrido', models.TextField()),
                ('id_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.control')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=255)),
                ('explicacion', models.TextField()),
                ('id_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.control')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rol')),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
    ]
