# Generated by Django 5.1.3 on 2024-11-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_control_anio_alter_control_ciclo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='explicacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
